export interface IRegisterUser {
  requestorEmail: string,
  requestorName: string,
  Criticality: string,
  requestingTeam: string,
  requestingTeamLocation: string,
  dataUsage: string,
  criticalityReason: string,
  howIndexWillBeUsed: string,
  requiredApplications: string,
  historyRequired: string,
  indexType: string,
  blendComponents: string,
  indexProvider: string,
  requiredUniverse: string,
  returnType: string,
  constituentsRequired: string,
  baseCurrency: string,
  indexName: string,
  vendorId: string,
  isWACIDataRequired: string,
  indexCostApproval: string,
  allergapproverEmailies: string,
  requiredHistoryDate: Date
}
